#!/usr/bin/env python
from popen2 import popen2
from time import sleep

PERIOD = 5
data = None

while True:
    o, i = popen2("osascript -e 'tell application \"iTunes\" to if player state is playing then name of current track & \"\n\" & artist of current track & \"\n\" & album of current track'")
    newdata = o.readlines()
    if data != newdata:
        data = newdata
        try:
            popen2("growlnotify -m \"" + data[1] + data[2] + "\" -t \"" + data[0] + "\"")
        except:
            pass

    sleep(PERIOD)

